#
# Common configuration infomations for all platforms
#
DRV	= mr_sas_il

ONUTSDIR = .
CROSS_KERNEL_HEADERS = -I /usr/include -I $(ONUTSDIR)/common -I$ $(ONUTSDIR)/intel
KFLAGS_COMMON += $(CROSS_KERNEL_HEADERS)
KFLAGS_SUNCC += -erroff=E_STATEMENT_NOT_REACHED,E_INTEGER_OVERFLOW_DETECTED

include version
DFLAGS	= -DDEBUG -DDEBUG_LEVEL=1
#
# Driver configuration
#
CFGFLAGS = -Unotdef -UNEVER -UGEM_GCC_RUNTIME \
	   -UMODULE \
	   -DDDI_PM_RESUME=DDI_PM_RESUME_OBSOLETE \
	   -DDDI_PM_SUSPEND=DDI_PM_SUSPEND_OBSOLETE \
	   -D__unused=" " -DCOMPAT_SOLARIS


LDFLAGS	+= -dy -N misc/scsi
